import * as THREE from 'three';

const LEVELS = [
  {title:'Kenali AKL',q:'AKL adalah singkatan dari jurusan apa di SMK PINTAR?',type:'choice',opts:['Akuntansi dan Lembaga','Akomodasi Keuangan Lembaga','Administrasi Keuangan Lokal']},
  {title:'Bisnis Daring & Pemasaran',q:'Menurutmu, keterampilan apa yang dipelajari di jurusan BDP dan mengapa menarik?',type:'essay'},
  {title:'Dunia Perhotelan',q:'Ceritakan pelayanan ramah seperti apa yang penting di bidang Perhotelan (PH).',type:'essay'},
  {title:'Kreator Teknologi',q:'Apa yang ingin kamu buat atau pelajari jika masuk jurusan Rekayasa Perangkat Lunak (RPL)?',type:'essay'},
  {title:'Teknik Otomotif',q:'Menurutmu, apa peran Teknisi Otomotif (TO) dalam kehidupan sehari-hari?',type:'essay'},
  {title:'Teknik Pengelasan',q:'Mengapa keselamatan kerja sangat penting dalam jurusan Teknik Pengelasan (TP)?',type:'essay'},
  {title:'Pilihan Masa Depan',q:'Setelah lulus SMP, kamu mau melanjutkan ke mana? Ceritakan alasanmu.',type:'essay'},
  {title:'Jurusan Impian',q:'Jika masuk SMK PINTAR, kamu mau mengambil jurusan apa? Mengapa?',type:'essay'},
  {title:'Suaramu untuk SMK PINTAR',q:'Jurusan apa yang kamu inginkan agar ada di SMK PINTAR?',type:'essay'},
  {title:'Mimpi Besarmu',q:'Apa hobi dan cita-citamu? Tulis secara jujur dari hati. Semoga SMK PINTAR menjadi jembatan meraih suksesmu!',type:'essay'}
];
const state={name:'',phone:'',level:1,gems:0,total:0,running:false,paused:false,answers:[],lastX:0};
const $=s=>document.querySelector(s); const screens=['welcome','game','quiz','leaderboard','complete','paused'];
function show(id){screens.forEach(x=>$('#'+x).classList.toggle('active',x===id));}
function goal(){return Math.min(10,5+state.level);}
function updateHUD(){ $('#level-label').textContent=state.level;$('#gem-label').textContent=state.gems;$('#gem-goal').textContent=goal();}
function maskPhone(p){return p.slice(0,5)+'••••'+p.slice(-3)}

// Three.js scene made from simple 3D shapes: no proprietary game assets required.
const canvas=$('#game-canvas'), renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));
const scene=new THREE.Scene();scene.background=new THREE.Color('#7edaf8');scene.fog=new THREE.Fog('#8edcf3',21,70);
const camera=new THREE.PerspectiveCamera(58,1,.1,100);camera.position.set(0,4.6,8.6);camera.lookAt(0,.4,-10);
scene.add(new THREE.HemisphereLight(0xfff5df,0x499254,2.8));const sun=new THREE.DirectionalLight(0xffffff,2.1);sun.position.set(6,12,7);scene.add(sun);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(25,160),new THREE.MeshStandardMaterial({color:0xd88042,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.z=-45;scene.add(floor);
for(const x of [-2.15,2.15]){const rail=new THREE.Mesh(new THREE.BoxGeometry(.12,.1,155),new THREE.MeshStandardMaterial({color:0x69452f}));rail.position.set(x,.06,-45);scene.add(rail)}
for(let z=5;z>-145;z-=1.5){const tie=new THREE.Mesh(new THREE.BoxGeometry(5,.1,.25),new THREE.MeshStandardMaterial({color:0x7b4227}));tie.position.set(0,.08,z);scene.add(tie)}
const deco=[];for(let z=2;z>-135;z-=7){for(const x of [-5,5]){const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.22,.33,2.1,7),new THREE.MeshStandardMaterial({color:0x814728}));trunk.position.set(x,1,z);scene.add(trunk);const leaf=new THREE.Mesh(new THREE.SphereGeometry(1.25,10,8),new THREE.MeshStandardMaterial({color:0x3eae5d}));leaf.scale.y=.75;leaf.position.set(x,2.55,z);scene.add(leaf);deco.push(trunk,leaf)}}
const player=new THREE.Group();const shirt=new THREE.Mesh(new THREE.BoxGeometry(.74,.9,.42),new THREE.MeshStandardMaterial({color:0x4a69df}));shirt.position.y=1.05;player.add(shirt);const head=new THREE.Mesh(new THREE.SphereGeometry(.37,14,10),new THREE.MeshStandardMaterial({color:0x9a5438}));head.position.y=1.77;player.add(head);for(const x of[-.23,.23]){const leg=new THREE.Mesh(new THREE.BoxGeometry(.18,.72,.2),new THREE.MeshStandardMaterial({color:0x26365e}));leg.position.set(x,.36,0);player.add(leg)}player.position.z=3.2;scene.add(player);
let gems=[],obstacles=[],clock=new THREE.Clock(),spawnTimer=0;
function diamond(x,z){const m=new THREE.Mesh(new THREE.OctahedronGeometry(.30),new THREE.MeshStandardMaterial({color:0x19d9ff,emissive:0x007fae,emissiveIntensity:.65,metalness:.35,roughness:.15}));m.position.set(x,.83,z);scene.add(m);gems.push(m)}
function obstacle(x,z){const m=new THREE.Mesh(new THREE.BoxGeometry(1.15,1.12,.55),new THREE.MeshStandardMaterial({color:0xe24b53}));m.position.set(x,.56,z);scene.add(m);obstacles.push(m)}
function startLevel(){state.gems=0;state.running=true;state.paused=false;gems.forEach(g=>scene.remove(g));obstacles.forEach(o=>scene.remove(o));gems=[];obstacles=[];spawnTimer=0;player.position.x=0;updateHUD();show('game');clock.start();requestAnimationFrame(loop)}
function addObjects(){const lane=[-1.35,0,1.35][Math.floor(Math.random()*3)];diamond(lane,-28);if(Math.random()>.47)obstacle([-1.35,0,1.35].filter(x=>x!==lane)[Math.floor(Math.random()*2)],-34)}
function collect(g){scene.remove(g);gems.splice(gems.indexOf(g),1);state.gems++;state.total++;updateHUD();if(state.gems>=goal())finishLevel()}
function finishLevel(){state.running=false;$('#quiz-level').textContent=state.level;const l=LEVELS[state.level-1];$('#quiz-title').textContent=l.title;$('#quiz-question').textContent=l.q;const q=$('#quiz-options'),ta=$('#essay'),card=$('.quiz-card');q.innerHTML='';ta.value='';card.classList.toggle('essay',l.type==='essay');if(l.type==='choice')l.opts.forEach((o,i)=>{const b=document.createElement('button');b.textContent=o;b.onclick=()=>{q.querySelectorAll('button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');};q.append(b)});$('#quiz-submit').textContent=state.level===10?'Selesai & Simpan 🏆':'Kirim & Lanjut Level →';show('quiz')}
function hit(o){return Math.abs(o.position.z-player.position.z)<.62&&Math.abs(o.position.x-player.position.x)<.72}
function loop(){if(!state.running)return;const d=Math.min(clock.getDelta(),.05),speed=8+state.level*.55;spawnTimer+=d;if(spawnTimer>1.08){spawnTimer=0;addObjects()}player.position.x+=(state.lastX-player.position.x)*Math.min(1,d*12);player.rotation.z=(state.lastX-player.position.x)*-.25;player.position.y=.1+Math.abs(Math.sin(performance.now()*.012))*0.055;[...gems].forEach(g=>{g.position.z+=speed*d;g.rotation.y+=d*5;if(g.position.z>9) {scene.remove(g);gems.splice(gems.indexOf(g),1)} else if(Math.abs(g.position.z-player.position.z)<.72&&Math.abs(g.position.x-player.position.x)<.75)collect(g)});[...obstacles].forEach(o=>{o.position.z+=speed*d;if(o.position.z>10){scene.remove(o);obstacles.splice(obstacles.indexOf(o),1)}else if(hit(o)){scene.remove(o);obstacles.splice(obstacles.indexOf(o),1);state.gems=Math.max(0,state.gems-2);updateHUD();}});renderer.render(scene,camera);requestAnimationFrame(loop)}
function resize(){const w=canvas.clientWidth,h=canvas.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();renderer.render(scene,camera);
function move(dir){state.lastX=Math.max(-1.35,Math.min(1.35,state.lastX+dir*1.35));}$('#left-btn').onclick=()=>move(-1);$('#right-btn').onclick=()=>move(1);let touchStart;canvas.addEventListener('touchstart',e=>touchStart=e.touches[0].clientX,{passive:true});canvas.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-touchStart;if(Math.abs(dx)>22)move(Math.sign(dx));},{passive:true});addEventListener('keydown',e=>{if(e.key==='ArrowLeft')move(-1);if(e.key==='ArrowRight')move(1)});
$('#player-form').onsubmit=e=>{e.preventDefault();const phone=$('#student-phone').value.trim();if(!/^\+62\d{8,13}$/.test(phone)){alert('Gunakan nomor WhatsApp dengan format +628123456789');return}state.name=$('#student-name').value.trim();state.phone=phone;startLevel()};
$('#quiz-submit').onclick=()=>{const l=LEVELS[state.level-1];const answer=l.type==='essay'?$('#essay').value.trim():$('#quiz-options .selected')?.textContent;if(!answer){alert('Silakan isi jawabanmu terlebih dahulu.');return}state.answers.push({level:state.level,topic:l.title,answer});if(state.level===10){saveScore();$('#final-score').textContent=state.total;$('#complete-text').textContent=`Terima kasih, ${state.name}! Jawabanmu telah tersimpan.`;show('complete')}else{state.level++;startLevel()}};
function pause(){if(!state.running)return;state.running=false;show('paused')}$('#pause-btn').onclick=pause;$('#resume').onclick=()=>{show('game');state.running=true;clock.start();requestAnimationFrame(loop)};$('#exit-game').onclick=()=>{state.running=false;show('welcome')};
$('#restart').onclick=()=>{Object.assign(state,{level:1,gems:0,total:0,answers:[]});startLevel()};document.querySelectorAll('[data-open="leaderboard"]').forEach(b=>b.onclick=()=>{loadBoard();show('leaderboard')});document.querySelectorAll('[data-close="leaderboard"]').forEach(b=>b.onclick=()=>show(state.running?'game':'welcome'));
async function loadBoard(){const list=$('#leaderboard-list');list.innerHTML='<li class="loading">Memuat skor...</li>';try{const r=await fetch('/api/leaderboard');const data=await r.json();const rows=data.scores||JSON.parse(localStorage.getItem('smkScores')||'[]');renderBoard(rows)}catch{renderBoard(JSON.parse(localStorage.getItem('smkScores')||'[]'))}}
function renderBoard(rows){const list=$('#leaderboard-list');list.innerHTML='';rows.sort((a,b)=>b.score-a.score).slice(0,20).forEach((x,i)=>{const li=document.createElement('li'),info=document.createElement('span'),score=document.createElement('b'),small=document.createElement('small');info.textContent=`${['🥇','🥈','🥉'][i]||i+1} ${x.name}`;small.textContent=` (${maskPhone(x.phone)})`;info.append(small);score.textContent=`💎 ${x.score}`;li.append(info,score);list.append(li)});if(!rows.length)list.innerHTML='<li class="loading">Belum ada skor. Jadilah yang pertama!</li>'}
async function saveScore(){const data={name:state.name,phone:state.phone,score:state.total,level:10,answers:state.answers,playedAt:new Date().toISOString()};const local=JSON.parse(localStorage.getItem('smkScores')||'[]');local.push(data);localStorage.setItem('smkScores',JSON.stringify(local));try{await fetch('/api/leaderboard',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})}catch{ /* local leaderboard remains available offline */ }}
